name: Deploy Apps
# Run on pushes to dev/main or PR
on:
  # Pull request hook without any config. Launches for every pull request
  pull_request:
  # Launches for pushes to main or dev
  push:
    branches:
      - main
      - development
  # Run manually to version/production deployment/github releases
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REPO_NAME_ALPHANUMERIC: safereactapps
  HUSKY: 0

jobs:
  pr:
    name: Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/setup-env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1

      - name: Test, Build, Deploy PR
        run: |
          npx nx affected --target=test
          npx nx affected --target=build 
          npx nx affected --target=deploy:pr
        env:
          PR_NUMBER: ${{ github.event.number }}
          REVIEW_BUCKET_NAME: ${{ secrets.AWS_REVIEW_BUCKET_NAME }}
          REACT_APP_TENDERLY_ORG_NAME: ${{ secrets.REACT_APP_TENDERLY_ORG_NAME }}
          REACT_APP_TENDERLY_SIMULATE_ENDPOINT_URL: ${{ secrets.REACT_APP_TENDERLY_SIMULATE_ENDPOINT_URL }}
          REACT_APP_TENDERLY_PROJECT_NAME: ${{ secrets.REACT_APP_TENDERLY_PROJECT_NAME }}
          REACT_APP_MMI_BACKEND_BASE_URL: ${{ secrets.MMI_BACKEND_BASE_URL }}
          REACT_APP_MMI_ENVIRONMENT: ${{ secrets.MMI_ENVIRONMENT }}
          REACT_APP_WALLETCONNECT_PROJECT_ID: ${{ secrets.REACT_APP_WALLETCONNECT_PROJECT_ID_DEVSTAGING }}
          REACT_APP_RAMP_APIKEY: ${{ secrets.REACT_APP_RAMP_APIKEY }}

      - name: 'PRaul: Comment PR with app URLs'
        if: success() && github.event.number
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message: |
            * [Drain Account App](${{ env.REVIEW_FEATURE_URL }}/drain-safe/)
            * [RAMP Network App](${{ env.REVIEW_FEATURE_URL }}/ramp-network/)
            * [Sign-In With Ethereum Delegate Manager App](${{ env.REVIEW_FEATURE_URL }}/siwe-delegate-manager/)
            * [Tx Builder App](${{ env.REVIEW_FEATURE_URL }}/tx-builder/)
            * [WalletConnect app](${{ env.REVIEW_FEATURE_URL }}/wallet-connect/)
            * [MMI App](${{ env.REVIEW_FEATURE_URL }}/mmi/)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
        env:
          REVIEW_FEATURE_URL: https://pr${{ github.event.number }}--${{ env.REPO_NAME_ALPHANUMERIC }}.review-react-hr.5afe.dev

  deploy:
    name: Deploy Dev/Staging
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1

      - name: Test and Build
        run: |
          npx nx affected --target=test --parallel
          npx nx affected --target=build --parallel
        env:
          REACT_APP_TENDERLY_ORG_NAME: ${{ secrets.REACT_APP_TENDERLY_ORG_NAME }}
          REACT_APP_TENDERLY_SIMULATE_ENDPOINT_URL: ${{ secrets.REACT_APP_TENDERLY_SIMULATE_ENDPOINT_URL }}
          REACT_APP_TENDERLY_PROJECT_NAME: ${{ secrets.REACT_APP_TENDERLY_PROJECT_NAME }}
          REACT_APP_MMI_BACKEND_BASE_URL: ${{ secrets.MMI_BACKEND_BASE_URL }}
          REACT_APP_MMI_ENVIRONMENT: ${{ secrets.MMI_ENVIRONMENT }}
          REACT_APP_WALLETCONNECT_PROJECT_ID: ${{ secrets.REACT_APP_WALLETCONNECT_PROJECT_ID_DEVSTAGING }}
          REACT_APP_RAMP_APIKEY: ${{ secrets.REACT_APP_RAMP_APIKEY }}

      # Script to deploy to the dev environment
      - name: 'Deploy to S3: Develop'
        if: github.ref == 'refs/heads/development'
        run: npx nx affected --target=deploy:s3
        env:
          BUCKET_NAME: ${{ secrets.AWS_DEV_BUCKET_NAME }}

      # Script to deploy to staging environment
      - name: 'Deploy to S3: Staging'
        if: github.ref == 'refs/heads/main'
        run: npx nx affected --base=last-release --target=deploy:s3
        env:
          BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}/current

  release:
    name: Production release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: main

      - uses: ./.github/actions/setup-env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Generate promotions repo token
        id: promotions_token
        continue-on-error: true
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.PROMOTIONS_APP_ID }}
          private-key: ${{ secrets.PROMOTIONS_APP_PRIVATE_KEY }}
          repositories: ${{ secrets.PROMOTIONS_REPO }}
          permission-actions: write

      - name: 'Deploy production'
        uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          promotions-token: ${{ steps.promotions_token.outputs.token }}
          promotions-repo: ${{ github.repository_owner }}/${{ secrets.PROMOTIONS_REPO }}
          bucket-name: ${{ secrets.STAGING_BUCKET_NAME }}/releases
          react-app-tenderly-org-name: ${{ secrets.REACT_APP_TENDERLY_ORG_NAME }}
          react-app-tenderly-project-name: ${{ secrets.REACT_APP_TENDERLY_PROJECT_NAME }}
          react-app-tenderly-simulate-endpoint-url: ${{ secrets.REACT_APP_TENDERLY_SIMULATE_ENDPOINT_URL }}
          react-app-mmi-backend-base-url: ${{ secrets.MMI_BACKEND_BASE_URL }}
          react-app-mmi-environment: ${{ secrets.MMI_ENVIRONMENT }}
          react-app-walletconnect-project-id: ${{ secrets.REACT_APP_WALLETCONNECT_PROJECT_ID }}
          react-app-ramp-api: ${{ secrets.REACT_APP_RAMP_APIKEY }}
